{% set name = "ward" %}
{% set version = "0.65.0b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ward-{{ version }}.tar.gz
  sha256: 4f086c746b0d3d4464cf8ddea54f11fa08e02a784d0fda5bdc9b7f9c9fa63db0

build:
  number: 1
  entry_points:
    - ward = ward._run:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - click >=7,<9
    - click-completion >=0.5.2,<0.6.0
    - click-default-group >=1.2.2,<2.0.0
    - cucumber-tag-expressions >=2.0.0,<5.0.0
    - dataclasses >=0.7,<0.9  # [py==36]
    - pluggy >=0.13.1,<2.0.0
    - pprintpp >=0.4.0,<0.5.0
    - python >=3.6
    - rich >=10.0.0,<11.0.0
    - tomli >=1.0.0,<2.0.0

test:
  imports:
    - ward
  commands:
    - pip check
    - ward --help
  requires:
    - pip

about:
  home: https://wardpy.com
  doc_url: https://ward.readthedocs.io/en/latest/
  dev_url: https://github.com/darrenburns/ward
  summary: A modern Python testing framework
  license: MIT
  license_file: LICENSE
  description: |
    Ward is a Python testing framework with a focus on productivity and
    readability. It gives you the tools you need to write well-documented and
    scalable tests. With Ward, you can describe your tests using strings instead
    of function names, and also use plain assert statements, with no need to
    remember assert* method names. Ward provides beautiful output that focuses
    on readability. It also manages test dependencies using a simple but
    powerful fixture system, while parameterising testing, which allows you to
    run a single test on multiple inputs. Ward has support for testing async
    code, and is supported on MacOS, Linux, and Windows. Ward is configurable
    with pyproject.toml, but works out-of-the-box with sensible defaults. It is
    also extendable via a plugin system (coming soon). Above all, Ward is speedy
    – Ward’s suite of ~300 tests completes in ~0.4 seconds on my machine.

extra:
  recipe-maintainers:
    - thewchan
